# Generated by Django 5.1.4 on 2025-01-17 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_jobposting_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True, related_name="saved_jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
