# Generated by Django 5.1.4 on 2025-01-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_forgotpasswordrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPasswordRequest',
        ),
    ]
