version: '3.9'

services:
  django:
    build: .
    container_name: django-web
    ports:
      - "8081:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: >
      sh -c "./wait-for-it.sh db:5432 -- 
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./staticfiles:/app/staticfiles
      - ./staticfiles:/code/staticfiles
    networks:
      - django-web_network

  db:
    image: postgres:16.6-alpine
    container_name: django-web_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django-web_network



volumes:
  postgres_data:
  static_volume:

networks:
  django-web_network:
    driver: bridge
