# Generated by Django 5.1.4 on 2025-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons/")),
                ("Salary", models.FloatField()),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("part-time", "Part-time"),
                            ("full-time", "Full-time"),
                        ],
                        default="full-time",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "job",
            },
        ),
    ]
