# Generated by Django 5.1.4 on 2025-01-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Jobs",
        ),
    ]
